name: Linter

on:
  push:
    paths:
    - 'lua/**'
  pull_request:
    paths:
    - 'lua/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Download GluaFixer 1.20.1
      run: |
        curl -o glualint.zip -L https://github.com/FPtje/GLuaFixer/releases/download/1.20.1/glualint-1.20.1-linux.zip
        unzip glualint.zip

    - name: Lint Code
      run: ./glualint lua